### ISSUE TITLE
ConsulClient.ApplyConfig breaks Mono

### ISSUE THREAD

**Issue by gdavison** [PlayFab/consuldotnet#59]
Commit cc8c37bef28f206ea3e2e11556f32eeba4b33fdd has broken consuldotnet v0.6.4.3 on Mono. `WebRequestHandler.ClientCertificates` throws a `NotImplementedException` in released versions of Mono.

**Comment by highlyunavailable** [comment]
Ouch, that's nasty. Thanks for reporting this, I'll see what I can do to fix it up. It wasn't getting hit before because if the cert was empty (which is the vast majority of the cases) it never tried to clear the handler, but if someone had tried to use this function on Mono, it would have crashed the same way.

**Comment by gdavison** [comment]
It feels a little hackish, but simply wrapping the certificate operations in a catch NotImplementedException block works.

**Comment by highlyunavailable** [comment]
I think that's what I will have to do. Out of curiosity are you using the Nuget package or compiling?

I was thinking of adding a conditional [Obsolete] attributes to the property for Mono to prevent use and just make the setter/getter do nothing under mono with a runtime check but that doesn't help if you are using the precompiled binaries.

**Comment by highlyunavailable** [comment]
Actually I can just propagate the exception to the setter in the config object so it fails if you try to set it explicitly only, and skip trying to reconfigure the handler if running on mono. Seems fairly clean to me.

**Comment by highlyunavailable** [comment]
I this is fixed - the tests now run successfully under Mono on Linux.

It does feel a bit hackish but it should at least throw a useful `PlatformUnsupportedException` if you try to set client certs under Mono, and not try to set them in the event handler if under Mono. I've cut a package as [0.6.4.5](https://www.nuget.org/packages/Consul/0.6.4.5).

**Comment by gdavison** [comment]
I was using the NuGet package. I'm still getting a `NotImplementedException` with 0.6.4.5. I'll investigate some more, as there was some weirdness with downloading the packages, but it did also fail on travis-ci

**Comment by highlyunavailable** [comment]
Hm, I can't get Travis set up right now because while I maintain this repo I don't actually have admin on it.

What's interesting here is I'm able to repro the error if I make a new project with the nuget package attached, which makes sense because the nuget package was compiled on VS2015 but if I run the tests it's compiled on Mono, which IFDEFs this out.

I shall continue to investigate.

**Comment by highlyunavailable** [comment]
It is because the runtime check is backwards:

https://github.com/PlayFab/consuldotnet/blob/master/Consul/Client.cs#L47

Should be: `return Type.GetType("Mono.Runtime") == null;`

**Comment by highlyunavailable** [comment]
So, for CI, this is an interesting challenge. I use `#if` to cut the offending code out on Mono entirely so you can't even set it, but only if compiled under Mono. However, this means that tests pass perfectly well _if compiled on Mono_ but would break if the Nuget package (compiled with MSBuild) is used. What a weird scenario, and I definitely would not have caught this particular issue if I'd just compiled under Mono on Travis, though I would have caught the original issue.

I'm waiting for Nuget to index [0.6.4.6](https://www.nuget.org/packages/Consul/0.6.4.6) so I can try it out but this should ACTUALLY fix it. Sorry about that!

**Comment by gdavison** [comment]
Yes, that's got it! My Travis build is green :) Thanks for the fix.

It's definitely an odd case. Using the NuGet package is so convenient, though!
